### ISSUE TITLE
Facing problems while running the glide up command

### ISSUE THREAD

**Issue by PraveenkumarDonga** [intelsdi-x/snap-plugin-lib-go#49]
Hi!
I am looking into the plugins creation:
I am getting the Errors.
Could anyone please help me with this?

Specifications: 
glide version v0.12.3
go version go1.6.2 linux/amd64
System: Ubuntu 16.04

Thanks
![selection_006](https://cloud.githubusercontent.com/assets/8088246/20795309/86b3f6e2-b7f6-11e6-9bc1-16e803666414.png)

**Comment by marcin-krolik** [comment]
@PraveenkumarDonga I think it may be related to your `GOPATH` setting. Can you show how your `GOPATH` looks like? Looking at your example I assume it should be `~/golang/glide` in order to properly execute `glide up`

I checked fetching dependencies for `snap-plugin-lib-go` with go1.7 and go1.7.2 and it works fine. I'm using `glide` in `v0.12.3`

**Comment by PraveenkumarDonga** [comment]
Hi!
It got solved. it is problem with GOPATH only I guess. 
Its is working(glide up).
And while building the plug-ins I am getting this error.  I guess this is because of packages.
So do we need to install the packages separately. 
If that is the case, then could you please tell me how to install those packages.

Thanks,
Praveen
![selection_007](https://cloud.githubusercontent.com/assets/8088246/20885371/7cc422ba-bb16-11e6-828c-4e8dbb48f425.png)
